server:
   port: 8761

eureka:
   instance:
     hostname: localhost
   server:
     enableSelfPreservation: false
   client:
     registerWithEureka: false
     fetchRegistry: false
     serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.26.128:3306/account_db?useSSL=false
    #url: jdbc:mysql://192.168.121.5:3306/account_db?useSSL=false
    username: root
    password: root
  rabbitmq:
      host: 47.93.193.177
      port: 5672
      username: admin
      password: root